/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function readAlbumFile(path: string): string
export function writeAlbumFile(path: string, albumJsonStr: string): void
export function getWorkspaceAlbums(workspacePath: string): string
export function createAlbum(workspace: string, path: string, discNum: number): void
export function commitAlbumPrepare(workspacePath: string, albumPath: string): string
export function commitAlbum(workspacePath: string, albumPath: string): void
export function publishAlbum(workspacePath: string, albumPath: string): void
